### ISSUE TITLE
Norway problem in yaml output from xkbcli list

### ISSUE THREAD

**Issue by hickford** [xkbcommon/libxkbcommon#268]
> Anyone who uses YAML long enough will eventually get burned when attempting to abbreviate Norway.

https://news.ycombinator.com/item?id=17359376

YAML output from `xkbcli list`

```yaml
- layout: no
  variant: ''
  brief: no
  description: Norwegian
  iso639: [nor, nob, nno]
  iso3166: []
```

Output of PyYAML's `yaml.safe_load`

```python
{'layout': False,
 'variant': '',
 'brief': False,
 'description': 'Norwegian',
 'iso639': ['nor', 'nob', 'nno'],
 'iso3166': []},
```
