### ISSUE TITLE
[XKB-769] Abandoning keytypes file "(unnamed)" from .gitkeep

### ISSUE THREAD

**Issue by dcunited001** [xkbcommon/libxkbcommon#388]
I'm customizing `.config/xkb` in KDE Wayland. I'm running into a few problems, but I'm not sure what's going on or whether the XKB-769 error is the actual issue. Given the error message, it's failing to parse something in `types.c`, but even after deleting the .gitkeep files, it's still failing.

Also, my approach to remapping the media keys is misguided (it will be tough to support across various hardware i know). Any help on this would be greatly appreciated. Thanks.

### Directory Structure

My directory structure is below. some directories are missing, though I've noticed that this can cause some problems. One of them involves `.gitkeep` files in the the `~/.config/xkb` directory, which is something I've run into before. I think that `xkbcommon` attempts to parse them anyways, but I just removed them and it doesn't seem to make a difference.  Are there any other files here that will cause problems?

 The xkbregistry output is at the end. I can update later with more info from `xkbcli`, but I have to move on for now.

```
/home/me/.config/xkb
├── 2022.test
│   ├── rules
│   │   ├── evdev.bak.xml
│   │   ├── evdev.test
│   │   ├── foo.xml.test
│   │   └── options
│   └── symbols
│       └── io
├── 20230510-xkbcomp-out.xkb
├── fdsa.sh
├── fdsa.sh~
├── io.altgr-intl.keyboard
├── io.altgr-intl.xkb
├── keymap
│   └── .gitkeep
├── rules
│   ├── evdev
│   ├── evdev.xml
│   └── rules.xml
├── symbols
│   ├── fmedia
│   ├── io
│   └── underspace
├── .testing
│   ├── altgr-intl.xkb.eg
│   ├── io.altgr-intl.keyboard
│   ├── io.altgr-intl.xkb
│   ├── io.fdsa
│   ├── us.altgr-intl.xkb
│   └── xkbcli.xkb
└── types
└── .gitkeep
```  

### Reloading XKB

XKB compilation output when triggered from KWin. I get this to run by toggling "Configure Keyboards" in system-settings and hitting apply.

```
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-338]         /home/dc/.config/xkb
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-338]         /usr/share/X11/xkb
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-338] 2 include paths could not be added:
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-338]         /home/dc/.xkb
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-338]         /etc/xkb
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: [XKB-769] Abandoning keytypes file "(unnamed)"
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: Failed to compile xkb_types
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: Failed to compile keymap
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: Unrecognized RMLVO variant "ctrl:hyper_capscontrol" was ignored
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: Unrecognized RMLVO variant "lvl3:menu_switch" was ignored
Oct 17 08:38:19 kratos kwin_wayland[27224]: kwin_xkbcommon: XKB: Unrecognized RMLVO variant "lvl3:ralt_alt" was ignored
```

I don't expect much help on the KDE issues, since that's separate, but i've included this here anyways.

.config/kxkbrc

```config
[$Version]
update_info=kxkb.upd:remove-empty-lists,kxkb.upd:add-back-resetoptions,kxkb_variants.upd:split-variants

[Layout]
DisplayNames=
LayoutList=us
Options=lv3:ralt_alt,ctrl:hyper_capscontrol,lv3:menu_switch,custom:types,fmedia:mute_f17
ResetOldOptions=true
Use=true
VariantList=
```

### KcCGST

.config/xkb/symbols/underspace

```c++
// -*- mode: c++; aphelia-mode: -1 -*-
// partial xkb_symbols "underspace:shift_underscore" {
partial xkb_symbols "shift_underscore" {
  key<SPCE>{[space, underscore, space, underscore]};
};

// partial xkb_symbols "underspace:altgr_underscore" {
partial xkb_symbols "altgr_underscore" {
  key<SPCE>{[space, space, underscore, underscore]};
};
```

### RMVLO/Evdev

.config/xkb/rules/evdev

```
! option = symbols
  underspace:shift_underscore    = +underspace(shift_underscore)
  underspace:altgr_underscore    = +underspace(altgr_underscore)
  
! option = symbols
  fmedia:mute_f17       = +fmedia(mute_f17)
  fmedia:voldown_f18    = +fmedia(voldown_f18)

! include %S/evdev
```

.config/xkb/rules/evdev.xml

```xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">
<xkbConfigRegistry version="1.1">
  <modelList>
  </modelList>
  <layoutList>
    <layout>
      <configItem>
        <name>io</name>
        <shortDescription>io</shortDescription>
        <description>IO Keyboard</description>
        <languageList>
          <iso639Id>eng</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>intl</name>
            <shortDescription>io-intl</shortDescription>
            <description>IO Keyboard (Intl With Dead Keys)</description>
          </configItem>
        </variant>
        <variant>
          <configItem>
            <name>altgr-intl</name>
            <shortDescription>io-altgr-intl</shortDescription>
            <description>IO Keyboard (AltGr Intl With Dead Keys)</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
  </layoutList>
  <optionList>
    <group allowMultipleSelection="false">
      <configItem>
        <name>underspace</name>
        <description>Type Underscore with the Space Bar</description>
      </configItem>
      <option>
        <configItem>
          <name>underspace:shift_underscore</name>
          <description>Make Shift+[AltGr]+Space An Underscore (problems in emacs)</description>
        </configItem>
      </option>
      <option>
        <configItem>
          <name>underspace:altgr_underscore</name>
          <description>Make AltGr+[Shift]+Space An Underscore (less problems in emacs)</description>
        </configItem>
      </option>
    </group>
    <group allowMultipleSelection="true">
      <configItem>
        <name>fmedia</name>
        <description>Reuse Media Keys as additional function keys</description>
      </configItem>
      <option>
        <configItem>
          <name>fmedia:mute_f17</name>
          <description>fdsa</description>
        </configItem>
      </option>
      <option>
        <configItem>
          <name>fmedia:voldown_f18</name>
          <description>fdsa</description>
        </configItem>
      </option>
    </group>
  </optionList>
</xkbConfigRegistry>

```

### Option Groups

 `xkbcli list | yq -y '.option_groups[-3:]'`

```yaml
- name: custom
description: Miscellaneous options
allows_multiple: true
options:
- name: custom:types
brief: ''
description: Use user-defined custom XKB types
- name: underspace
description: Type Underscore with the Space Bar
allows_multiple: false
options:
- name: underspace:shift_underscore
brief: ''
description: Make Shift+[AltGr]+Space An Underscore (problems in emacs)
- name: underspace:altgr_underscore
brief: ''
description: Make AltGr+[Shift]+Space An Underscore (less problems in emacs)
- name: fmedia
description: Reuse Media Keys as additional function keys
allows_multiple: true
options:
- name: fmedia:mute_f17
brief: ''
description: fdsa
- name: fmedia:voldown_f18
brief: ''
description: fdsa
```

### Layouts

The `io` layouts/variants seem to be available to fcitx5:

`xkbcli list | yq -y '.layouts[-4:]'`

```yaml
- layout: custom
variant: ''
brief: custom
description: A user-defined custom Layout
iso639:
- und
iso3166: []
- layout: io
variant: ''
brief: io
description: IO Keyboard
iso639:
- eng
iso3166: []
- layout: io
variant: intl
brief: io-intl
description: IO Keyboard (Intl With Dead Keys)
iso639:
- eng
iso3166: []
- layout: io
variant: altgr-intl
brief: io-altgr-intl
description: IO Keyboard (AltGr Intl With Dead Keys)
iso639:
- eng
iso3166: []
```
